name: Setup Go
description: Setup Go environment and module cache

inputs:
  go-version:
    description: "Go version to install (optional if go-version-file is used)"
    required: false
    default: ""
  go-version-file:
    description: "Path to go.mod file"
    required: false
    default: ""
  cache-dependency-path:
    description: "Path to go.sum file"
    required: false
    default: ""
  cache:
    description: "Whether to enable caching"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        cache: ${{ inputs.cache }}
