# .github/actions/deploy/action.yml
name: Setup dependencies
description: Setup dependencies

inputs:
outputs:

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    - uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.working-directory }}/go.mod
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    - uses: ./.github/actions/common/aws.yml

    - uses: ./.github/actions/common/nx.yml

    - uses: ./.github/actions/idea-collector/dependencies.yml