name: On pull request Idea Collector

on: 
  workflow_call:
    inputs:
      project:
        type: string
        required: false
        default: 'idea-collector'
      plan_infra:
        type: boolean
        required: false
        default: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check-frontend:
    name: Frontend Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nx
        uses: ./.github/actions/common/nx

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Lint Frontend
        shell: bash
        run: pnpm nx run idea-collector-frontend:lint

      - name: Build Frontend
        shell: bash
        run: pnpm nx run idea-collector-frontend:build

  plan-infra:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: ${{ inputs.plan_infra == true && (inputs.project == 'idea-collector-infra' || inputs.project == 'idea-collector') }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/idea-collector/setup

      - id: init
        shell: bash
        run: pnpm nx run idea-collector-infra:init

      - id: validate
        shell: bash
        run: pnpm nx run idea-collector-infra:validate

      - id: plan
        shell: bash
        run: pnpm nx run idea-collector-infra:plan
