name: On pull request

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history so Nx can diff

      - uses: ./.github/actions/common/nx

      - id: detect
        uses: ./.github/actions/common/detect
  idea-collector:
    uses: ./.github/workflows/idea-collector.on_pull_request.yml
    needs: detect
    if: contains(fromJson(needs.detect.outputs.services), 'idea-collector') || contains(fromJson(needs.detect.outputs.services), 'idea-collector-infra') || contains(fromJson(needs.detect.outputs.services), 'idea-collector-frontend')
    with:
      project: 'idea-collector'
      plan_infra: ${{ contains(fromJson(needs.detect.outputs.services), 'idea-collector-infra') }}
  commifra:
    uses: ./.github/workflows/commifra.on_pull_request.yml
    needs: detect
    if: contains(fromJson(needs.detect.outputs.services), 'commifra')
  

    
